apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.auth.name }}
  namespace: {{ .Release.namespace }}
data:
  serviceName: {{ .Values.service.auth.name | quote }}
  servicePort: {{ .Values.service.auth.port | quote }}
