apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.mariadb.name }}
  namespace: {{ .Release.namespace }}
data:
  serviceName: {{ .Values.service.mariadb.name | quote }}
  servicePort: {{ .Values.service.mariadb.port | quote }}
