{{- $containerPort := "1111" -}}
{{- $deploymentName := "detective-auth" -}}
{{- $initDeploymentName := "init-detective-auth" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "detective-platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.image.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $deploymentName }}
      {{- include "detective-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $deploymentName }}
        {{- include "detective-platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "detective-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $deploymentName }}
          image: {{ .Values.image.repository }}/auth-service:{{ .Values.image.auth.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ $containerPort }}
              protocol: TCP
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.jwtAccessTokenSecretName }}
                  key: jwk
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.jwtRefreshTokenSecretName }}
                  key: jwk
            - name: DATABASE_GRPC_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.dgraph.name }}
                  key: serviceName
            - name: DATABASE_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.dgraph.name }}
                  key: servicePort
      initContainers:
        - name: {{ $initDeploymentName }}
          image: busybox:{{ .Values.image.busybox.tag }}
          command: ['sh', '-c', "until nslookup {{ .Values.service.dgraph.alphaName }}; do echo waiting for {{ .Values.service.dgraph.alphaName }}; sleep {{ .Values.initContainerStartupDelay }}; done"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.auth.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.service.auth.name }}
    {{- include "detective-platform.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.auth.port }}
      targetPort: {{ $containerPort }}
      protocol: TCP
  selector:
    app: {{ $deploymentName }}
