{{- $containerPort := "3003" -}}
{{- $deploymentName := "detective-provisioning" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "detective-platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ $deploymentName }}
      {{- include "detective-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $deploymentName }}
        {{- include "detective-platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "detective-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $deploymentName }}
          image: {{ .Values.image.repository }}/provisioning-service:{{ .Values.image.provisioning.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ $containerPort }}
              protocol: TCP
          env:
            - name: SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.jwtAccessTokenSecretName }}
                  key: jwk
            - name: ALGORITHM
              value: "sha256"
            - name: DGRAPH_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.dgraph.name }}
                  key: serviceName
            - name: DGRAPH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.dgraph.name }}
                  key: servicePort
            - name: AUTH_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.auth.name }}
                  key: serviceName
            - name: AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.auth.name }}
                  key: servicePort
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.payment.stripe.secretName }}
                  key: secret
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.payment.stripe.secretName }}
                  key: publishableKey
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.payment.stripe.secretName }}
                  key: webhookSecret
            - name: STRIPE_CHANGE_PAYMENT_PORTAL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.payment.stripe.secretName }}
                  key: changePaymentPortal
            - name: MAIL_SERVER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.secretName }}
                  key: emailServer
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.secretName }}
                  key: emailServerPort
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.secretName }}
                  key: emailUsername
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.secretName }}
                  key: emailPassword
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.secretName }}
                  key: emailFrom
            - name: MAIL_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.secretName }}
                  key: emailFromName
            - name: COMPANY_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.secretName }}
                  key: emailTemplateCompanyName
            - name: COMPANY_LOCATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.secretName }}
                  key: emailTemplateCompanyLocation
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.provisioning.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.service.provisioning.name }}
    {{- include "detective-platform.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.provisioning.port }}
      targetPort: {{ $containerPort }}
      protocol: TCP
  selector:
    app: {{ $deploymentName }}
