{{- $containerPort := "3007" -}}
{{- $deploymentName := "detective-upload" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "detective-platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ $deploymentName }}
      {{- include "detective-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $deploymentName }}
        {{- include "detective-platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "detective-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $deploymentName }}
          image: {{ .Values.image.repository }}/upload-service:{{ .Values.image.upload.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ $containerPort }}
              protocol: TCP
          env:
            - name: SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.jwtAccessTokenSecretName }}
                  key: jwk
            - name: ALGORITHM
              value: "HS256"
            - name: BUCKET_XID
              value: "7982569f-9424-11ed-93f1-27dd7c3b61c3"
            - name: AUTH_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.auth.name }}
                  key: serviceName
            - name: AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.auth.name }}
                  key: servicePort
            - name: DGRAPH_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.dgraph.name }}
                  key: serviceName
            - name: DGRAPH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.dgraph.name }}
                  key: servicePort
            - name: KAFKA_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.kafka.name }}
                  key: serviceName
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.kafka.name }}
                  key: servicePort
            - name: TRINO_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.trino.name }}
                  key: serviceName
            - name: TRINO_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.trino.name }}
                  key: servicePort
            - name: MINIO_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.minio.name }}
                  key: serviceName
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.minio.name }}
                  key: servicePort
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.minio.secretName }}
                  key: minioAccessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.minio.secretName }}
                  key: minioSecretKey
            - name: CONVERT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.upload.secretName }}
                  key: convertApiSecret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.upload.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.service.upload.name }}
    {{- include "detective-platform.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.upload.port }}
      targetPort: {{ $containerPort }}
      protocol: TCP
  selector:
    app: {{ $deploymentName }}
