# Default values for the detective-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Enables monitoring tools like Kafdrop & DGraph Ratel
enableMonitoringTools: false

ingress:
  # MANDATORY: Domain needs to be set when installing chart (via local-values.yaml or CLI)
  domain:
  name: detective-ingress
  class: nginx
  apiPrefix: /api
  apiVersionPrefixV1: /v1
  tls:
    enabled: true
    issuerName: letsencrypt
    issuerUrl: https://acme-staging-v02.api.letsencrypt.org/directory
    secretName: tls-cert-secret
    acmeEmail: founders@detective.solutions

auth:
  jwtAccessTokenSecretName: jwt-access-token-secret
  # MANDATORY: Access token secret needs to be set when installing chart (via local-values.yaml or CLI)
  jwtAccessTokenSecretValue:
  jwtRefreshTokenSecretName: jwt-refresh-token-secret
  # MANDATORY: Access token secret needs to be set when installing chart (via local-values.yaml or CLI)
  jwtRefreshTokenSecretValue:

image:
  # MANDATORY: Registry token needs to be set when installing chart (via local-values.yaml or CLI)
  registryToken:
  pullSecrets: [ name: docker-registry-credentials ]
  repository: quay.io/detective.solutions
  pullPolicy: IfNotPresent
  replicaCount: 2
  # Image tags default to the chart's appVersion if empty
  auth:
    tag:
  catalog:
    tag:
  detectiveClient:
    tag:
  masking:
    tag:
  query:
    tag:
  transaction:
    tag:
  trinoCoordinator:
    tag:
  versionControl:
    tag:
  websocketGateway:
    tag:

  # Set metadata for third-party images which are not bound to the chart's appVersion
  dgraph:
    tag: v21.12.0@sha256:3b55ea83fffeb8909031552e504831068bb438ab7bb31471f3c16bd4ff99c1e4
  kafka:
    version: 3.2.0
    protocolVersion: 3.2
    replicaCount: 3
    logLevel: "INFO"
  kafdrop:
    tag: 3.30.0@sha256:5337c9e0e2dee204bdde53e90cf97001f44fb9e8c3380340436efa844901a3f4
  ratel:
    tag: v21.12.0@sha256:f34ac9708541c56dc922b40c537d7b113fead503bd788815da8da0a10a35038f
  redis:
    tag: 7.0.4-alpine@sha256:7c9e7c305125c68354c4902ed09a3c6da96436a5a2929b73f29748d56cf8e3c3
  busybox:
    tag: stable@sha256:bbb248c803ff97f51db3b37a2a604a6270cd2ee1ca9266120aeccb3b19ce80d2
  kafkacat:
    tag: 7.1.3@sha256:9659eda18f99d56ad7f0a7732a4b66fac20036b894e4137604275feaa8b3c49d

service:
  dgraph:
    alphaName: detective-dgraph-alpha-public
    zeroName: detective-dgraph-zero-public
    alphaHttpPort: 8080
    alphaGrpcPort: 9080
    zeroHttpPort: 6080
    zeroGrpcPort: 5080
    ingressPath: graphql
  ratel:
    name: detective-dgraph-ratel-service
    port: 8000
  kafdrop:
    name: detective-kafdrop-service
    port: 9000
  kafka:
    name: detective-kafka-cluster
    fullName: detective-kafka-cluster-kafka-bootstrap
    port1: 9092
    port2: 9093
  redis:
    name: detective-redis-service
    port: 6379
  auth:
    name: detective-auth-service
    port: 1111
    ingressPath: v1/auth
  catalog:
    name: detective-catalog-service
    port: 3003
    ingressPath: v1/catalog
  detectiveClient:
    name: detective-client-service
    port: 80
  trinoCoordinator:
    name: detective-trino-coordinator-service
    port: 8083
  websocketGateway:
    name: detective-websocket-gateway-service
    port: 7777
    ingressPath: ws

configMap:
  dgraph:
    name: dgraph-podconfig
  kafka:
    name: kafka-podconfig
  redis:
    name: redis-podconfig
  trino:
    name: trino-podconfig

nameOverride: ""
fullnameOverride: ""

initContainerStartupDelay: 120

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
