# Default values for the detective-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Enables monitoring tools like Kafdrop & DGraph Ratel
enableMonitoringTools: false

ingress:
  name: detective-ingress
  domain:


auth:
  jwtAccessTokenSecretName: jwt-access-token-secret
  # MANDATORY: Access token secret need to be set when installing chart (via local-values.yaml or CLI)
  jwtAccessTokenSecretValue:
  jwtRefreshTokenSecretName: jwt-refresh-token-secret
  # MANDATORY: Access token secret need to be set when installing chart (via local-values.yaml or CLI)
  jwtRefreshTokenSecretValue:

image:
  # MANDATORY: Registry token needs to be set when installing chart (via local-values.yaml or CLI)
  registryToken:
  pullSecrets: [ name: docker-registry-credentials ]
  repository: quay.io/detective.solutions
  pullPolicy: IfNotPresent
  replicaCount: 2
  # Overrides image tags whose default is the chart appVersion.
  detectiveClient:
    tag: 1.0.0-beta-DET-890
  auth:
    tag: 1.0.0-beta-DET-890
  websocketGateway:
    tag: 1.0.0-beta-DET-890
  trino-coordinator:
    tag: 1.0.0-beta
  masking:
    tag: 1.0.0-beta
  catalog:
    tag: 1.0.0-beta
  query:
    tag: 1.0.0-beta
  dgraph:
    tag: v21.12.0@sha256:3b55ea83fffeb8909031552e504831068bb438ab7bb31471f3c16bd4ff99c1e4
  kafka:
    version: 3.2.0
    protocolVersion: 3.2
    replicaCount: 3
  kafdrop:
    tag: 3.30.0@sha256:5337c9e0e2dee204bdde53e90cf97001f44fb9e8c3380340436efa844901a3f4
  ratel:
    tag: v21.12.0@sha256:f34ac9708541c56dc922b40c537d7b113fead503bd788815da8da0a10a35038f

service:
  detectiveClient:
    name: detective-client-service
    port: 80
    ingressPath: /
  auth:
    name: detective-auth-service
    port: 1111
    ingressPath: /v1/auth
  websocketGateway:
    name: detective-websocket-gateway-service
    port: 7777
    ingressPath: /ws
  trinoCoordinator:
    name: detective-trino-coordinator-service
    port: 8083
  catalog:
    name: detective-catalog-service
    port: 3003
  query:
    name: detective-query-service
    port: 7799
  dgraph:
    alphaName: detective-dgraph-alpha-public
    zeroName: detective-dgraph-zero-public
    alphaHttpPort: 8080
    alphaGrpcPort: 9080
    zeroHttpPort: 6080
    zeroGrpcPort: 5080
    ingressPath: /graphql
  ratel:
    name: detective-dgraph-ratel-service
    port: 8000
  kafka:
    name: detective-kafka-cluster
    fullName: detective-kafka-cluster-kafka-bootstrap
    port1: 9092
    port2: 9093
  kafdrop:
    name: detective-kafdrop-service
    port: 9000
    ingressPath: /kafdrop

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
