apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "A valid docker registry token is required!" .Values.image.registryToken }}
