apiVersion: v1
kind: Secret
metadata:
  {{- with (index .Values.image.pullSecrets 0) }}
  name: {{ .name }}
  {{- end }}
  namespace: {{ .Release.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "A valid docker registry token is required!" .Values.image.registryToken }}
