apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.email.secretName }}
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  emailServer: {{ required "A valid email server address is required!" .Values.email.server | b64enc }}
  emailServerPort: {{ required "A valid email server port value is required!" .Values.email.port | toString | b64enc }}
  emailUsername: {{ required "A valid email username is required!" .Values.email.username | b64enc }}
  emailPassword: {{ required "A valid email password is required!" .Values.email.password | b64enc }}
  emailFrom: {{ required "A valid email sender address is required!" .Values.email.fromAddress | b64enc }}
  emailFromName: {{ required "A valid email sender name is required!" .Values.email.fromName | b64enc}}
  emailTemplateCompanyName: {{ required "A valid email company name is required!" .Values.email.templateCompanyName | b64enc }}
  emailTemplateCompanyLocation: {{ required "A valid email company location is required!" .Values.email.templateCompanyLocation | b64enc }}

