apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.jwtAccessTokenSecretName }}
  namespace: {{ .Release.namespace }}
type: nginx.org/jwk
data:
  jwk: {{ required "A valid access token secret is required!" .Values.auth.jwtAccessTokenSecretValue }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.jwtRefreshTokenSecretName }}
  namespace: {{ .Release.namespace }}
type: nginx.org/jwk
data:
  jwk: {{ required "A valid refresh token secret is required!" .Values.auth.jwtRefreshTokenSecretValue }}

