apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.mariadb.name }}
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  mySqlRootPassword: {{ required "A valid MYSQL root password is required!" .Values.mariadb.mySqlRootPassword | b64enc }}
  mySqUser: {{ required "A valid MYSQL user is required!" .Values.mariadb.mySqUser | b64enc }}
  mySqlPassword: {{ required "A valid MYSQL password is required!" .Values.mariadb.mySqlPassword | b64enc }}
  mySqlDatabase: {{ required "A valid MYSQL database name is required!" .Values.mariadb.mySqlDatabase | b64enc }}
