apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.payment.stripe.secretName }}
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  secret: {{ required "A valid Stripe Secret is required!" .Values.payment.stripe.secret }}
  publishableKey: {{ required "A valid Stripe Publishable Key is required!" .Values.payment.stripe.publishableKey }}
  webhookSecret: {{ required "A valid Stripe Webhook Secret is required!" .Values.payment.stripe.webhookSecret }}
  changePaymentPortal: {{ required "A valid Change Payment Portal value is required!" .Values.payment.stripe.changePaymentPortal }}
