apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.upload.secretName }}
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  convertApiSecret: {{ required "A valid CONVERT API SECRET is required!" .Values.minio.minioAccessKey | b64enc }}