apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.upload.secretName }}
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  accessKey: {{ required "A valid MINIO ACCESS KEY is required!" .Values.upload.accessKey | b64enc }}
  secretKey: {{ required "A valid MINIO SECRET KEY is required!" .Values.upload.secretKey | b64enc }}
  convertApiSecret: {{ required "A valid CONVERT API SECRET is required!" .Values.upload.convertApiSecret | b64enc }}