apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.upload.secretName }}
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  convertApiSecret: {{ required "A valid CONVERT API SECRET is required!" .Values.minio.convertApiSecret | b64enc }}
  minioSecretKey: {{ required "A valid MINIO SECRET KEY is required!" .Values.minio.minioSecretKey | b64enc }}
  minioAccessKey: {{ required "A valid MINIO ACCESS KEY is required!" .Values.minio.minioAccessKey | b64enc }}