apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.payment.stripe.secretName }}
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  secret: {{ required "A valid Stripe Secret is required!" .Values.payment.stripe.secret | b64enc }}
  publishableKey: {{ required "A valid Stripe Publishable Key is required!" .Values.payment.stripe.publishableKey | b64enc }}
  webhookSecret: {{ required "A valid Stripe Webhook Secret is required!" .Values.payment.stripe.webhookSecret | b64enc }}
  changePaymentPortal: {{ required "A valid Change Payment Portal value is required!" .Values.payment.stripe.changePaymentPortal | b64enc }}
