{{- if .Values.enableMonitoringTools -}}

{{- $containerPort := "8000" -}}
{{- $deploymentName := "dgraph-ratel" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $deploymentName }}
  template:
    metadata:
      labels:
        app: {{ $deploymentName }}
    spec:
      containers:
        - name: {{ $deploymentName }}
          image: dgraph/ratel:{{ .Values.image.ratel.tag }}
          ports:
            - containerPort: {{ $containerPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ratel.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.service.ratel.name }}
    {{- include "detective-platform.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.ratel.port }}
      targetPort: {{ $containerPort }}
      protocol: TCP
  selector:
    app: {{ $deploymentName }}

{{- end }}
