apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.minio.name }}
  namespace: {{ .Release.namespace }}
data:
  serviceName: {{ .Values.service.minio.name | quote }}
  servicePort: {{ .Values.service.minio.port | quote }}
